### ISSUE TITLE
Feature 1: User Can Generate a Random Word with Definition

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/Wordy#1]
## ⚙️ Feature

> ##### Users can generate and view a random word along with its definition when they press the 'Click Here!' button.

## 📐 Functionality

> ##### - 'Click Here!' button will take users to a page that shows the new word that has been generated along with its definition.

## 🖼️ Wireframes

> ##### Mobile View:

![Feature 1 - Mobile](https://user-images.githubusercontent.com/89041368/147978616-6581210c-c1a5-40f4-8e40-3e5477a5ace6.JPG)

> ##### Desktop View:
![Feature 1 - Desktop](https://user-images.githubusercontent.com/89041368/147978625-e72db900-efcb-4bc2-bdc0-25d3948664dd.JPG)

## ✅ Task List

- [x] Add a div[data-view="main-page"] to the HTML.
- [x] Add a nav bar with logo
- [x] Create home view with button for 'Click Here!'
- [x] Ensure view matches wireframe for mobile and desktop.
- [x] Listen for 'click' events on the 'Click Here!' button
  - [x] Takes user to div[data-view="new-word"] view
  - [x] Create XMLHttpRequest object to retrieve random word and definition from API
- [x] Remove all unnecessary CSS styling
- [x] Test functionality in private browsing session
- [x] Resolve errors
