### ISSUE TITLE
Feature 6: User Can Generate New Word

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/Wordy#12]
## ⚙️ Feature

> ##### User can generate a new word if they do not want to save the current word.

## 📐 Functionality

> ##### - 'NEW' button will generate a new random word and its definition.

## 🖼️ Wireframes

> ##### Mobile View:
![Feature 2 - Mobile Ver2](https://user-images.githubusercontent.com/89041368/149394746-7f6372c6-a75c-4948-9517-f12b1117a564.JPG)

> ##### Desktop View:
![Feature 2 - Desktop Ver2](https://user-images.githubusercontent.com/89041368/149394758-083c0dce-fa2e-492a-bc78-02bb43f2be5a.JPG)

## ✅ Task List

- [x] Add 'NEW' button to current card view
- [x] Ensure view matches wireframe for mobile and desktop.
- [x] Listen for 'click' events on the 'NEW' button.
  - [x] Place the retrieved values into new object
  - [x] Add `nextWordId` to the object
  - [x] Increment `nextWordId` on the data model
- [x] Remove all unnecessary CSS styling
- [x] Test functionality in private browsing session
- [x] Resolve errors
