### ISSUE TITLE
Feature 2: User Can Save a Word to their Study List 

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/Wordy#2]
## ⚙️ Feature

> ##### Users can save a word to add to their study list.

## 📐 Functionality

> ##### - 'SAVE' button will save the randomly generated word and its definition into the Study List page.

## 🖼️ Wireframes

> ##### Mobile View:
![Feature 2 - Mobile](https://user-images.githubusercontent.com/89041368/149395247-a593fc79-f090-4298-824e-7e083ba34484.JPG)

> ##### Desktop View:
![Feature 2 - Desktop](https://user-images.githubusercontent.com/89041368/149395251-0efd84d1-88b4-460c-96e0-abc63155981c.JPG)

## ✅ Task List

- [x] Add a div[data-view="new-word"] to the HTML.
- [x] Create card view with 'SAVE' button
- [x] Ensure view matches wireframe for mobile and desktop.
- [x] Listen for 'click' events on the 'SAVE' button.
  - [x] Place the retrieved values into new object
  - [x] Add `nextWordId` to the object
  - [x] Increment `nextWordId` on the data model
- [x] Verify that "saved" words are saved on local storage along with previously saved words upon reload.
- [x] Verify that each new word receives an incrementing `nextWordId`
- [x] Remove all unnecessary CSS styling
- [x] Test functionality in private browsing session
- [x] Resolve errors
