### ISSUE TITLE
Feature 3: User Can See a List of Words They Are Currently Studying

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/Wordy#3]
## ⚙️ Feature

> ##### User can see a list of words that they have saved.

## 📐 Functionality

> ##### Once a word is saved, users can go to their 'Study List' to see a complete list of words they are currently studying.

## 🖼️ Wireframes

> ##### 
![Feature 3 - Mobile](https://user-images.githubusercontent.com/89041368/148431883-c4ed1ec5-86ed-44ca-b5b2-2618641d274a.JPG)
Mobile View:

> ##### Desktop View:
![Feature 3 - Desktop](https://user-images.githubusercontent.com/89041368/148431898-22ac6104-1b7d-4db4-85a7-b4fe6baf46c0.JPG)

## ✅ Task List

- [x] Add a sibling `div[data-view="study-list"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="study-list"]` element in the HTML.
- [x] Add a placeholder `li` element to the unordered list in the HTML and style to match wireframe.
- [x] Check that the Study List view matches wireframe on both mobile and desktop.
- [x] Define a function that takes in a single `savedCard` object and returns a DOM tree that matches the placeholder word in the HTML.
- [x] Use a loop to create a DOM tree for each `savedCard` in the data model and append it to the Study List page when `DOMContentLoaded` event is fired.
- [x] Remove placeholder HTML word once it is confirmed that each newly saved word is successfully getting appended to the DOM in the Study List page.
- [x] Add a link to the navigation bar for 'List'.
- [x] Ensure that saving a card automatically shows the new word on the Study List page without reloading the page.
- [x] Show a message when there are no words in the list.
- [x] Ensure that refreshing the browser shows the same view as before refreshing.
- [x] Delete all unnecessary CSS styling.
- [x] Test the app in private browsing tab.
- [x] Fix all errors, delete console logs and commented lines of code.
