### ISSUE TITLE
Feature 4: User Can Study Words on Their Study List as Flash Cards

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/Wordy#4]
## ⚙️ Feature

> ##### User can study the words that they have saved.

## 📐 Functionality

> ##### Clicking the 'Study' button at the bottom of the Study List page will take user to a flash-card study page where they can flip cards to reveal the current word's definition. Clicking 'Back' takes users back to the word and clicking 'Next' will take users to the next word in the list.

## 🖼️ Wireframes

> ##### Mobile View: 
![Feature 4 - Mobile](https://user-images.githubusercontent.com/89041368/148625484-9f431cc4-2240-40ca-a554-cdedcc8acbfe.JPG)

> ##### Desktop View: 
![Feature 4 - Desktop](https://user-images.githubusercontent.com/89041368/148625489-2e2e770a-c064-4ca3-b3f1-1ad72e2a337f.JPG)

## ✅ Task List

- [x] Create 'Study' button at the bottom of the Study List view.
- [x] Ensure all flashcard views match wireframe.
- [x] Listen for 'click' events on the 'Flip' button that "flips" the card to show the current word's definition. 
- [x] Listen for 'click' events on the 'Back' button that takes user back to the word view.
- [x] Listen for 'click' events on the 'Study' button that takes user to the first word in the `savedCards` array within the data object.
- [x] Listen for 'click' events on the 'Next' button that takes user to the next card in the `savedCards` array within the data object.
- [x] Once user reaches end of list, flashcard starts again from the top.
- [x] Ensure that refreshing the browser shows the same view as before refreshing.
- [x] Delete all unnecessary CSS styling.
- [x] Test the app in private browsing tab.
- [x] Fix all errors, delete console logs and commented lines of code.
