### ISSUE TITLE
Feature 5: User Can Delete a Word They Have Learned

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/Wordy#5]
## ⚙️ Feature

> ##### User can delete words that they have learned.

## 📐 Functionality

> ##### Clicking the trash icon located on the right hand side of each of the words in the Study List page will allow the user to remove the word from their Study List.

## 🖼️ Wireframes

> ##### Mobile View: 
![Feature 5 - Mobile](https://user-images.githubusercontent.com/89041368/149011280-38fb5e53-f3cf-40ef-91dd-33b2381b3c6d.JPG)

> ##### Desktop View: 
![Feature 5 - Desktop](https://user-images.githubusercontent.com/89041368/149011268-b0f5c43a-03ba-4d55-8555-e2cdd3562a19.JPG)

## ✅ Task List

- [x] Add a click target for deleting a word when the user is viewing the Study List.
- [x] Show a confirmation modal when the user clicks the trash icon.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the word from the data model and DOM tree from the page if the user clicks Delete.
- [x] Show the Study List list if the user clicks Delete.
- [x] Remove all unnecessary CSS styling.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
